export const Formats: FormatList = [
	{
		section: "PokèRogue Mod",
	},
	{
		name: "[Gen 9] PokeRogue Classic",
		mod: 'pokeroguec',
		searchShow: false,
		ruleset: [
			'Cancel Mod',
			'HP Percentage Mod',
			'PokeRogue Classic Rule',
			'PokeRogue EXP Tracker',
		],
		DefaultLevel: 1,
		MaxLevel: 999999,
		banlist: [],
	},
	{
		name: "[Gen 9] PokeRogue Classic Doubles",
		mod: 'pokeroguec',
		gameType: 'doubles',
		searchShow: false,
		ruleset: [
			'Cancel Mod',
			'HP Percentage Mod',
			'PokeRogue Classic Rule',
			'PokeRogue EXP Tracker',
		],
		DefaultLevel: 1,
		MaxLevel: 999999,
		banlist: [],
	},
	{
		name: "[Gen 9] PokeRogue Random",
		mod: 'pokeroguec',
		searchShow: false,
		ruleset: [
			'Cancel Mod',
			'HP Percentage Mod',
			'PokeRogue Classic Rule',
			'PokeRogue EXP Tracker',
		],
		DefaultLevel: 1,
		MaxLevel: 999999,
		banlist: [],
	},
	{
		name: "[Gen 9] PokeRogue Random Doubles",
		mod: 'pokeroguec',
		gameType: 'doubles',
		searchShow: false,
		ruleset: [
			'Cancel Mod',
			'HP Percentage Mod',
			'PokeRogue Classic Rule',
			'PokeRogue EXP Tracker',
		],
		DefaultLevel: 1,
		MaxLevel: 999999,
		banlist: [],
	},
	{
		section: "SGGame",
	},
	{
		name: "[Gen 9] SGGame Singles",
		mod: 'sggame',
		searchShow: false,
		ruleset: [
			'Cancel Mod',
			'HP Percentage Mod',
			'EXP Gain Mod',
			'Terastal Clause',
			'Dynamax Clause',
		],
		DefaultLevel: 1,
		MaxLevel: 999999,
		banlist: [],
	},
	{
		name: "[Gen 9] SGGame Doubles",
		mod: 'sggame',
		gameType: 'doubles',
		searchShow: false,
		ruleset: [
			'Cancel Mod',
			'HP Percentage Mod',
			'EXP Gain Mod',
			'Terastal Clause',
			'Dynamax Clause',
		],
		DefaultLevel: 1,
		MaxLevel: 999999,
		banlist: [],
	},
];
