type MultiZoneEntry = string | [string, string][];

// Countries with multiple timezones — each entry is [label, IANA timezone]
const MULTI_TIMEZONE_COUNTRIES: Record<string, MultiZoneEntry> = {
	'usa': [
		['Eastern (New York)', 'America/New_York'],
		['Central (Chicago)', 'America/Chicago'],
		['Mountain (Denver)', 'America/Denver'],
		['Pacific (Los Angeles)', 'America/Los_Angeles'],
		['Alaska', 'America/Anchorage'],
		['Hawaii', 'Pacific/Honolulu'],
	],
	'unitedstates': 'usa',
	'us': 'usa',
	'america': 'usa',
	'canada': [
		['Eastern (Toronto)', 'America/Toronto'],
		['Central (Winnipeg)', 'America/Winnipeg'],
		['Mountain (Edmonton)', 'America/Edmonton'],
		['Pacific (Vancouver)', 'America/Vancouver'],
		['Atlantic (Halifax)', 'America/Halifax'],
		['Newfoundland', 'America/St_Johns'],
	],
	'ca': 'canada',
	'australia': [
		['Eastern (Sydney/Melbourne)', 'Australia/Sydney'],
		['Central (Adelaide)', 'Australia/Adelaide'],
		['Western (Perth)', 'Australia/Perth'],
		['Queensland (Brisbane)', 'Australia/Brisbane'],
		['Northern Territory (Darwin)', 'Australia/Darwin'],
	],
	'au': 'australia',
	'russia': [
		['Moscow', 'Europe/Moscow'],
		['Yekaterinburg', 'Asia/Yekaterinburg'],
		['Omsk', 'Asia/Omsk'],
		['Krasnoyarsk', 'Asia/Krasnoyarsk'],
		['Irkutsk', 'Asia/Irkutsk'],
		['Yakutsk', 'Asia/Yakutsk'],
		['Vladivostok', 'Asia/Vladivostok'],
		['Kamchatka', 'Asia/Kamchatka'],
	],
	'ru': 'russia',
	'brazil': [
		['Brasília (São Paulo/Rio)', 'America/Sao_Paulo'],
		['Amazon (Manaus)', 'America/Manaus'],
		['Acre', 'America/Rio_Branco'],
		['Fernando de Noronha', 'America/Noronha'],
	],
	'br': 'brazil',
	'mexico': [
		['Central (Mexico City)', 'America/Mexico_City'],
		['Pacific (Mazatlán)', 'America/Mazatlan'],
		['Mountain (Chihuahua)', 'America/Chihuahua'],
		['Northwest (Tijuana)', 'America/Tijuana'],
	],
	'mx': 'mexico',
	'indonesia': [
		['Western (Jakarta)', 'Asia/Jakarta'],
		['Central (Makassar)', 'Asia/Makassar'],
		['Eastern (Jayapura)', 'Asia/Jayapura'],
	],
	'id': 'indonesia',
	'kazakhstan': [
		['West (Aktau)', 'Asia/Aqtau'],
		['East (Almaty)', 'Asia/Almaty'],
	],
	'kz': 'kazakhstan',
	'mongolia': [
		['Ulaanbaatar', 'Asia/Ulaanbaatar'],
		['Hovd', 'Asia/Hovd'],
	],
	'mn': 'mongolia',
	'chile': [
		['Santiago', 'America/Santiago'],
		['Easter Island', 'Pacific/Easter'],
	],
	'cl': 'chile',
	'spain': [
		['Madrid', 'Europe/Madrid'],
		['Canary Islands', 'Atlantic/Canary'],
	],
	'es': 'spain',
	'portugal': [
		['Lisbon', 'Europe/Lisbon'],
		['Azores', 'Atlantic/Azores'],
	],
	'pt': 'portugal',
	'newzealand': [
		['Auckland', 'Pacific/Auckland'],
		['Chatham Islands', 'Pacific/Chatham'],
	],
	'nz': 'newzealand',
	'ukraine': [
		['Kyiv', 'Europe/Kyiv'],
	],
	'ua': 'ukraine',
	'argentina': [
		['Buenos Aires', 'America/Argentina/Buenos_Aires'],
		['Mendoza', 'America/Argentina/Mendoza'],
		['Tucumán', 'America/Argentina/Tucuman'],
	],
	'ar': 'argentina',
	'ecuador': [
		['Quito (Mainland)', 'America/Guayaquil'],
		['Galápagos', 'Pacific/Galapagos'],
	],
	'ec': 'ecuador',
	'kiribati': [
		['Tarawa', 'Pacific/Tarawa'],
		['Phoenix Islands', 'Pacific/Enderbury'],
		['Line Islands', 'Pacific/Kiritimati'],
	],
	'ki': 'kiribati',
	'micronesia': [
		['Pohnpei', 'Pacific/Pohnpei'],
		['Chuuk', 'Pacific/Chuuk'],
		['Kosrae', 'Pacific/Kosrae'],
	],
	'fm': 'micronesia',
	'federstatesofmicronesia': 'micronesia',
	'congo': [
		['Kinshasa', 'Africa/Kinshasa'],
		['Lubumbashi', 'Africa/Lubumbashi'],
	],
	'drc': 'congo',
	'democraticrepublicofcongo': 'congo',
	'cd': 'congo',
};

// Single-timezone countries and city lookups
const SINGLE_TIMEZONES: Record<string, string> = {
	// Asia
	'india': 'Asia/Kolkata',
	'in': 'Asia/Kolkata',
	'china': 'Asia/Shanghai',
	'cn': 'Asia/Shanghai',
	'japan': 'Asia/Tokyo',
	'jp': 'Asia/Tokyo',
	'korea': 'Asia/Seoul',
	'southkorea': 'Asia/Seoul',
	'kr': 'Asia/Seoul',
	'northkorea': 'Asia/Pyongyang',
	'kp': 'Asia/Pyongyang',
	'pakistan': 'Asia/Karachi',
	'pk': 'Asia/Karachi',
	'bangladesh': 'Asia/Dhaka',
	'bd': 'Asia/Dhaka',
	'srilanka': 'Asia/Colombo',
	'lk': 'Asia/Colombo',
	'nepal': 'Asia/Kathmandu',
	'np': 'Asia/Kathmandu',
	'thailand': 'Asia/Bangkok',
	'th': 'Asia/Bangkok',
	'vietnam': 'Asia/Ho_Chi_Minh',
	'vn': 'Asia/Ho_Chi_Minh',
	'malaysia': 'Asia/Kuala_Lumpur',
	'my': 'Asia/Kuala_Lumpur',
	'singapore': 'Asia/Singapore',
	'sg': 'Asia/Singapore',
	'philippines': 'Asia/Manila',
	'ph': 'Asia/Manila',
	'uae': 'Asia/Dubai',
	'ae': 'Asia/Dubai',
	'unitedarabemirates': 'Asia/Dubai',
	'saudiarabia': 'Asia/Riyadh',
	'sa': 'Asia/Riyadh',
	'israel': 'Asia/Jerusalem',
	'il': 'Asia/Jerusalem',
	'turkey': 'Europe/Istanbul',
	'tr': 'Europe/Istanbul',
	'iran': 'Asia/Tehran',
	'ir': 'Asia/Tehran',
	'iraq': 'Asia/Baghdad',
	'iq': 'Asia/Baghdad',
	'afghanistan': 'Asia/Kabul',
	'af': 'Asia/Kabul',
	'myanmar': 'Asia/Rangoon',
	'burma': 'Asia/Rangoon',
	'mm': 'Asia/Rangoon',
	'cambodia': 'Asia/Phnom_Penh',
	'kh': 'Asia/Phnom_Penh',
	'laos': 'Asia/Vientiane',
	'la': 'Asia/Vientiane',
	'taiwan': 'Asia/Taipei',
	'tw': 'Asia/Taipei',
	'hongkong': 'Asia/Hong_Kong',
	'hk': 'Asia/Hong_Kong',
	'macau': 'Asia/Macau',
	'mo': 'Asia/Macau',
	'timor': 'Asia/Dili',
	'timorleste': 'Asia/Dili',
	'easttimor': 'Asia/Dili',
	'tl': 'Asia/Dili',
	'brunei': 'Asia/Brunei',
	'bn': 'Asia/Brunei',
	'maldives': 'Indian/Maldives',
	'mv': 'Indian/Maldives',
	'bhutan': 'Asia/Thimphu',
	'bt': 'Asia/Thimphu',
	'uzbekistan': 'Asia/Tashkent',
	'uz': 'Asia/Tashkent',
	'kyrgyzstan': 'Asia/Bishkek',
	'kg': 'Asia/Bishkek',
	'tajikistan': 'Asia/Dushanbe',
	'tj': 'Asia/Dushanbe',
	'turkmenistan': 'Asia/Ashgabat',
	'tm': 'Asia/Ashgabat',
	'azerbaijan': 'Asia/Baku',
	'az': 'Asia/Baku',
	'armenia': 'Asia/Yerevan',
	'am': 'Asia/Yerevan',
	'georgia': 'Asia/Tbilisi',
	'ge': 'Asia/Tbilisi',
	'jordan': 'Asia/Amman',
	'jo': 'Asia/Amman',
	'lebanon': 'Asia/Beirut',
	'lb': 'Asia/Beirut',
	'syria': 'Asia/Damascus',
	'sy': 'Asia/Damascus',
	'kuwait': 'Asia/Kuwait',
	'kw': 'Asia/Kuwait',
	'qatar': 'Asia/Qatar',
	'qa': 'Asia/Qatar',
	'oman': 'Asia/Muscat',
	'om': 'Asia/Muscat',
	'bahrain': 'Asia/Bahrain',
	'bh': 'Asia/Bahrain',
	'yemen': 'Asia/Aden',
	'ye': 'Asia/Aden',
	'cyprus': 'Asia/Nicosia',
	'cy': 'Asia/Nicosia',

	// Europe
	'uk': 'Europe/London',
	'unitedkingdom': 'Europe/London',
	'england': 'Europe/London',
	'gb': 'Europe/London',
	'france': 'Europe/Paris',
	'fr': 'Europe/Paris',
	'germany': 'Europe/Berlin',
	'de': 'Europe/Berlin',
	'italy': 'Europe/Rome',
	'it': 'Europe/Rome',
	'netherlands': 'Europe/Amsterdam',
	'nl': 'Europe/Amsterdam',
	'belgium': 'Europe/Brussels',
	'be': 'Europe/Brussels',
	'switzerland': 'Europe/Zurich',
	'ch': 'Europe/Zurich',
	'austria': 'Europe/Vienna',
	'at': 'Europe/Vienna',
	'sweden': 'Europe/Stockholm',
	'se': 'Europe/Stockholm',
	'norway': 'Europe/Oslo',
	'no': 'Europe/Oslo',
	'denmark': 'Europe/Copenhagen',
	'dk': 'Europe/Copenhagen',
	'finland': 'Europe/Helsinki',
	'fi': 'Europe/Helsinki',
	'poland': 'Europe/Warsaw',
	'pl': 'Europe/Warsaw',
	'greece': 'Europe/Athens',
	'gr': 'Europe/Athens',
	'romania': 'Europe/Bucharest',
	'ro': 'Europe/Bucharest',
	'hungary': 'Europe/Budapest',
	'hu': 'Europe/Budapest',
	'czechrepublic': 'Europe/Prague',
	'czechia': 'Europe/Prague',
	'cz': 'Europe/Prague',
	'slovakia': 'Europe/Bratislava',
	'sk': 'Europe/Bratislava',
	'croatia': 'Europe/Zagreb',
	'hr': 'Europe/Zagreb',
	'serbia': 'Europe/Belgrade',
	'rs': 'Europe/Belgrade',
	'bulgaria': 'Europe/Sofia',
	'bg': 'Europe/Sofia',
	'latvia': 'Europe/Riga',
	'lv': 'Europe/Riga',
	'estonia': 'Europe/Tallinn',
	'ee': 'Europe/Tallinn',
	'lithuania': 'Europe/Vilnius',
	'lt': 'Europe/Vilnius',
	'belarus': 'Europe/Minsk',
	'by': 'Europe/Minsk',
	'ireland': 'Europe/Dublin',
	'ie': 'Europe/Dublin',
	'iceland': 'Atlantic/Reykjavik',
	'is': 'Atlantic/Reykjavik',
	'luxembourg': 'Europe/Luxembourg',
	'lu': 'Europe/Luxembourg',
	'malta': 'Europe/Malta',
	'mt': 'Europe/Malta',
	'albania': 'Europe/Tirane',
	'al': 'Europe/Tirane',
	'northmacedonia': 'Europe/Skopje',
	'macedonia': 'Europe/Skopje',
	'mk': 'Europe/Skopje',
	'bosniaandherzegovina': 'Europe/Sarajevo',
	'bosnia': 'Europe/Sarajevo',
	'ba': 'Europe/Sarajevo',
	'montenegro': 'Europe/Podgorica',
	'me': 'Europe/Podgorica',
	'moldova': 'Europe/Chisinau',
	'md': 'Europe/Chisinau',
	'slovenia': 'Europe/Ljubljana',
	'si': 'Europe/Ljubljana',
	'kosovo': 'Europe/Belgrade',
	'xk': 'Europe/Belgrade',
	'liechtenstein': 'Europe/Vaduz',
	'li': 'Europe/Vaduz',
	'monaco': 'Europe/Monaco',
	'mc': 'Europe/Monaco',
	'sanmarino': 'Europe/San_Marino',
	'sm': 'Europe/San_Marino',
	'vatican': 'Europe/Vatican',
	'vaticancity': 'Europe/Vatican',
	'va': 'Europe/Vatican',
	'andorra': 'Europe/Andorra',
	'ad': 'Europe/Andorra',

	// Americas
	'colombia': 'America/Bogota',
	'co': 'America/Bogota',
	'peru': 'America/Lima',
	'pe': 'America/Lima',
	'venezuela': 'America/Caracas',
	've': 'America/Caracas',
	'bolivia': 'America/La_Paz',
	'bo': 'America/La_Paz',
	'paraguay': 'America/Asuncion',
	'py': 'America/Asuncion',
	'uruguay': 'America/Montevideo',
	'uy': 'America/Montevideo',
	'guyana': 'America/Guyana',
	'gy': 'America/Guyana',
	'suriname': 'America/Paramaribo',
	'sr': 'America/Paramaribo',
	'panama': 'America/Panama',
	'pa': 'America/Panama',
	'costarica': 'America/Costa_Rica',
	'cr': 'America/Costa_Rica',
	'cuba': 'America/Havana',
	'cu': 'America/Havana',
	'jamaica': 'America/Jamaica',
	'jm': 'America/Jamaica',
	'haiti': 'America/Port-au-Prince',
	'ht': 'America/Port-au-Prince',
	'dominicanrepublic': 'America/Santo_Domingo',
	'do': 'America/Santo_Domingo',
	'guatemala': 'America/Guatemala',
	'gt': 'America/Guatemala',
	'honduras': 'America/Tegucigalpa',
	'hn': 'America/Tegucigalpa',
	'elsalvador': 'America/El_Salvador',
	'sv': 'America/El_Salvador',
	'nicaragua': 'America/Managua',
	'ni': 'America/Managua',
	'belize': 'America/Belize',
	'bz': 'America/Belize',
	'bahamas': 'America/Nassau',
	'bs': 'America/Nassau',
	'barbados': 'America/Barbados',
	'bb': 'America/Barbados',
	'trinidadandtobago': 'America/Port_of_Spain',
	'trinidad': 'America/Port_of_Spain',
	'tt': 'America/Port_of_Spain',
	'puertorico': 'America/Puerto_Rico',
	'pr': 'America/Puerto_Rico',
	'antiguaandbarbuda': 'America/Antigua',
	'antigua': 'America/Antigua',
	'ag': 'America/Antigua',
	'saintlucia': 'America/St_Lucia',
	'lc': 'America/St_Lucia',
	'saintvincentandthegrenadines': 'America/St_Vincent',
	'saintvincent': 'America/St_Vincent',
	'vc': 'America/St_Vincent',
	'grenada': 'America/Grenada',
	'gd': 'America/Grenada',
	'saintkittsandnevis': 'America/St_Kitts',
	'saintkitts': 'America/St_Kitts',
	'kn': 'America/St_Kitts',
	'dominica': 'America/Dominica',
	'dm': 'America/Dominica',

	// Oceania
	'fiji': 'Pacific/Fiji',
	'fj': 'Pacific/Fiji',
	'papuanewguinea': 'Pacific/Port_Moresby',
	'png': 'Pacific/Port_Moresby',
	'pg': 'Pacific/Port_Moresby',
	'solomonislands': 'Pacific/Guadalcanal',
	'sb': 'Pacific/Guadalcanal',
	'vanuatu': 'Pacific/Efate',
	'vu': 'Pacific/Efate',
	'samoa': 'Pacific/Apia',
	'ws': 'Pacific/Apia',
	'tonga': 'Pacific/Tongatapu',
	'to': 'Pacific/Tongatapu',
	'palau': 'Pacific/Palau',
	'pw': 'Pacific/Palau',
	'marshallislands': 'Pacific/Majuro',
	'mh': 'Pacific/Majuro',
	'nauru': 'Pacific/Nauru',
	'nr': 'Pacific/Nauru',
	'tuvalu': 'Pacific/Funafuti',
	'tv': 'Pacific/Funafuti',
	'cookislands': 'Pacific/Rarotonga',
	'ck': 'Pacific/Rarotonga',
	'niue': 'Pacific/Niue',
	'nu': 'Pacific/Niue',
	'tonga': 'Pacific/Tongatapu',

	// Africa
	'southafrica': 'Africa/Johannesburg',
	'za': 'Africa/Johannesburg',
	'nigeria': 'Africa/Lagos',
	'ng': 'Africa/Lagos',
	'kenya': 'Africa/Nairobi',
	'ke': 'Africa/Nairobi',
	'egypt': 'Africa/Cairo',
	'eg': 'Africa/Cairo',
	'ghana': 'Africa/Accra',
	'gh': 'Africa/Accra',
	'ethiopia': 'Africa/Addis_Ababa',
	'et': 'Africa/Addis_Ababa',
	'tanzania': 'Africa/Dar_es_Salaam',
	'tz': 'Africa/Dar_es_Salaam',
	'morocco': 'Africa/Casablanca',
	'ma': 'Africa/Casablanca',
	'tunisia': 'Africa/Tunis',
	'tn': 'Africa/Tunis',
	'algeria': 'Africa/Algiers',
	'dz': 'Africa/Algiers',
	'libya': 'Africa/Tripoli',
	'ly': 'Africa/Tripoli',
	'sudan': 'Africa/Khartoum',
	'sd': 'Africa/Khartoum',
	'southsudan': 'Africa/Juba',
	'ss': 'Africa/Juba',
	'uganda': 'Africa/Kampala',
	'ug': 'Africa/Kampala',
	'zimbabwe': 'Africa/Harare',
	'zw': 'Africa/Harare',
	'zambia': 'Africa/Lusaka',
	'zm': 'Africa/Lusaka',
	'mozambique': 'Africa/Maputo',
	'mz': 'Africa/Maputo',
	'senegal': 'Africa/Dakar',
	'sn': 'Africa/Dakar',
	'angola': 'Africa/Luanda',
	'ao': 'Africa/Luanda',
	'madagascar': 'Indian/Antananarivo',
	'mg': 'Indian/Antananarivo',
	'rwanda': 'Africa/Kigali',
	'rw': 'Africa/Kigali',
	'cameroon': 'Africa/Douala',
	'cm': 'Africa/Douala',
	'ivorycoast': 'Africa/Abidjan',
	'cotedivoire': 'Africa/Abidjan',
	'ci': 'Africa/Abidjan',
	'mali': 'Africa/Bamako',
	'ml': 'Africa/Bamako',
	'burkinafaso': 'Africa/Ouagadougou',
	'bf': 'Africa/Ouagadougou',
	'guinea': 'Africa/Conakry',
	'gn': 'Africa/Conakry',
	'somalia': 'Africa/Mogadishu',
	'so': 'Africa/Mogadishu',
	'namibia': 'Africa/Windhoek',
	'na': 'Africa/Windhoek',
	'botswana': 'Africa/Gaborone',
	'bw': 'Africa/Gaborone',
	'mauritius': 'Indian/Mauritius',
	'mu': 'Indian/Mauritius',
	'seychelles': 'Indian/Mahe',
	'sc': 'Indian/Mahe',
	'niger': 'Africa/Niamey',
	'ne': 'Africa/Niamey',
	'chad': 'Africa/Ndjamena',
	'td': 'Africa/Ndjamena',
	'centralafricanrepublic': 'Africa/Bangui',
	'car': 'Africa/Bangui',
	'cf': 'Africa/Bangui',
	'gabon': 'Africa/Libreville',
	'ga': 'Africa/Libreville',
	'republicofcongo': 'Africa/Brazzaville',
	'congobrazz': 'Africa/Brazzaville',
	'cg': 'Africa/Brazzaville',
	'equatorialguinea': 'Africa/Malabo',
	'gq': 'Africa/Malabo',
	'burundi': 'Africa/Bujumbura',
	'bi': 'Africa/Bujumbura',
	'benin': 'Africa/Porto-Novo',
	'bj': 'Africa/Porto-Novo',
	'togo': 'Africa/Lome',
	'tg': 'Africa/Lome',
	'sierraleone': 'Africa/Freetown',
	'sl': 'Africa/Freetown',
	'liberia': 'Africa/Monrovia',
	'lr': 'Africa/Monrovia',
	'guineabissau': 'Africa/Bissau',
	'gw': 'Africa/Bissau',
	'gambia': 'Africa/Banjul',
	'gm': 'Africa/Banjul',
	'mauritania': 'Africa/Nouakchott',
	'mr': 'Africa/Nouakchott',
	'malawi': 'Africa/Blantyre',
	'mw': 'Africa/Blantyre',
	'lesotho': 'Africa/Maseru',
	'ls': 'Africa/Maseru',
	'eswatini': 'Africa/Mbabane',
	'swaziland': 'Africa/Mbabane',
	'sz': 'Africa/Mbabane',
	'djibouti': 'Africa/Djibouti',
	'dj': 'Africa/Djibouti',
	'eritrea': 'Africa/Asmara',
	'er': 'Africa/Asmara',
	'caboverde': 'Atlantic/Cape_Verde',
	'capeverde': 'Atlantic/Cape_Verde',
	'cv': 'Atlantic/Cape_Verde',
	'saotomeandprincipe': 'Africa/Sao_Tome',
	'saotome': 'Africa/Sao_Tome',
	'st': 'Africa/Sao_Tome',
	'comoros': 'Indian/Comoro',
	'km': 'Indian/Comoro',

	// Cities — Asia
	'mumbai': 'Asia/Kolkata',
	'delhi': 'Asia/Kolkata',
	'newdelhi': 'Asia/Kolkata',
	'bangalore': 'Asia/Kolkata',
	'bengaluru': 'Asia/Kolkata',
	'kolkata': 'Asia/Kolkata',
	'chennai': 'Asia/Kolkata',
	'hyderabad': 'Asia/Kolkata',
	'pune': 'Asia/Kolkata',
	'ahmedabad': 'Asia/Kolkata',
	'jaipur': 'Asia/Kolkata',
	'lucknow': 'Asia/Kolkata',
	'surat': 'Asia/Kolkata',
	'nagpur': 'Asia/Kolkata',
	'karachi': 'Asia/Karachi',
	'lahore': 'Asia/Karachi',
	'islamabad': 'Asia/Karachi',
	'dhaka': 'Asia/Dhaka',
	'kathmandu': 'Asia/Kathmandu',
	'colombo': 'Asia/Colombo',
	'kabul': 'Asia/Kabul',
	'tehran': 'Asia/Tehran',
	'baghdad': 'Asia/Baghdad',
	'dubai': 'Asia/Dubai',
	'abudhabi': 'Asia/Dubai',
	'sharjah': 'Asia/Dubai',
	'riyadh': 'Asia/Riyadh',
	'jeddah': 'Asia/Riyadh',
	'mecca': 'Asia/Riyadh',
	'medina': 'Asia/Riyadh',
	'doha': 'Asia/Qatar',
	'kuwaitcity': 'Asia/Kuwait',
	'muscat': 'Asia/Muscat',
	'beirut': 'Asia/Beirut',
	'damascus': 'Asia/Damascus',
	'amman': 'Asia/Amman',
	'jerusalem': 'Asia/Jerusalem',
	'telaviv': 'Asia/Jerusalem',
	'istanbul': 'Europe/Istanbul',
	'ankara': 'Europe/Istanbul',
	'izmir': 'Europe/Istanbul',
	'tashkent': 'Asia/Tashkent',
	'almaty': 'Asia/Almaty',
	'bishkek': 'Asia/Bishkek',
	'dushanbe': 'Asia/Dushanbe',
	'ashgabat': 'Asia/Ashgabat',
	'baku': 'Asia/Baku',
	'yerevan': 'Asia/Yerevan',
	'tbilisi': 'Asia/Tbilisi',
	'bangkok': 'Asia/Bangkok',
	'chiangmai': 'Asia/Bangkok',
	'hochiminhcity': 'Asia/Ho_Chi_Minh',
	'hochiminh': 'Asia/Ho_Chi_Minh',
	'hanoi': 'Asia/Ho_Chi_Minh',
	'phnompenh': 'Asia/Phnom_Penh',
	'vientiane': 'Asia/Vientiane',
	'yangon': 'Asia/Rangoon',
	'naypyidaw': 'Asia/Rangoon',
	'jakarta': 'Asia/Jakarta',
	'surabaya': 'Asia/Jakarta',
	'bali': 'Asia/Makassar',
	'denpasar': 'Asia/Makassar',
	'kualalumpur': 'Asia/Kuala_Lumpur',
	'kl': 'Asia/Kuala_Lumpur',
	'singaporecity': 'Asia/Singapore',
	'manila': 'Asia/Manila',
	'cebu': 'Asia/Manila',
	'taipei': 'Asia/Taipei',
	'hongkong': 'Asia/Hong_Kong',
	'macaucity': 'Asia/Macau',
	'beijing': 'Asia/Shanghai',
	'shanghai': 'Asia/Shanghai',
	'guangzhou': 'Asia/Shanghai',
	'shenzhen': 'Asia/Shanghai',
	'chengdu': 'Asia/Shanghai',
	'wuhan': 'Asia/Shanghai',
	'xian': 'Asia/Shanghai',
	'chongqing': 'Asia/Shanghai',
	'nanjing': 'Asia/Shanghai',
	'tianjin': 'Asia/Shanghai',
	'tokyo': 'Asia/Tokyo',
	'osaka': 'Asia/Tokyo',
	'kyoto': 'Asia/Tokyo',
	'yokohama': 'Asia/Tokyo',
	'nagoya': 'Asia/Tokyo',
	'sapporo': 'Asia/Tokyo',
	'fukuoka': 'Asia/Tokyo',
	'seoul': 'Asia/Seoul',
	'busan': 'Asia/Seoul',
	'incheon': 'Asia/Seoul',
	'pyongyang': 'Asia/Pyongyang',
	'ulaanbaatar': 'Asia/Ulaanbaatar',
	'thimphu': 'Asia/Thimphu',
	'male': 'Indian/Maldives',
	'dili': 'Asia/Dili',
	'bandarseribegawan': 'Asia/Brunei',
	'nicosia': 'Asia/Nicosia',

	// Cities — Europe
	'london': 'Europe/London',
	'paris': 'Europe/Paris',
	'berlin': 'Europe/Berlin',
	'munich': 'Europe/Berlin',
	'frankfurt': 'Europe/Berlin',
	'hamburg': 'Europe/Berlin',
	'cologne': 'Europe/Berlin',
	'rome': 'Europe/Rome',
	'milan': 'Europe/Rome',
	'naples': 'Europe/Rome',
	'turin': 'Europe/Rome',
	'madrid': 'Europe/Madrid',
	'barcelona': 'Europe/Madrid',
	'seville': 'Europe/Madrid',
	'valencia': 'Europe/Madrid',
	'lisbon': 'Europe/Lisbon',
	'porto': 'Europe/Lisbon',
	'amsterdam': 'Europe/Amsterdam',
	'rotterdam': 'Europe/Amsterdam',
	'brussels': 'Europe/Brussels',
	'antwerp': 'Europe/Brussels',
	'zurich': 'Europe/Zurich',
	'geneva': 'Europe/Zurich',
	'bern': 'Europe/Zurich',
	'vienna': 'Europe/Vienna',
	'stockholm': 'Europe/Stockholm',
	'gothenburg': 'Europe/Stockholm',
	'oslo': 'Europe/Oslo',
	'bergen': 'Europe/Oslo',
	'copenhagen': 'Europe/Copenhagen',
	'helsinki': 'Europe/Helsinki',
	'warsaw': 'Europe/Warsaw',
	'krakow': 'Europe/Warsaw',
	'wroclaw': 'Europe/Warsaw',
	'moscow': 'Europe/Moscow',
	'saintpetersburg': 'Europe/Moscow',
	'stpetersburg': 'Europe/Moscow',
	'kyiv': 'Europe/Kyiv',
	'kharkiv': 'Europe/Kyiv',
	'athens': 'Europe/Athens',
	'thessaloniki': 'Europe/Athens',
	'bucharest': 'Europe/Bucharest',
	'budapest': 'Europe/Budapest',
	'debrecen': 'Europe/Budapest',
	'prague': 'Europe/Prague',
	'brno': 'Europe/Prague',
	'bratislava': 'Europe/Bratislava',
	'zagreb': 'Europe/Zagreb',
	'belgrade': 'Europe/Belgrade',
	'novisad': 'Europe/Belgrade',
	'sofia': 'Europe/Sofia',
	'plovdiv': 'Europe/Sofia',
	'riga': 'Europe/Riga',
	'tallinn': 'Europe/Tallinn',
	'vilnius': 'Europe/Vilnius',
	'kaunas': 'Europe/Vilnius',
	'minsk': 'Europe/Minsk',
	'dublin': 'Europe/Dublin',
	'cork': 'Europe/Dublin',
	'reykjavik': 'Atlantic/Reykjavik',
	'luxembourg': 'Europe/Luxembourg',
	'luxembourgcity': 'Europe/Luxembourg',
	'valletta': 'Europe/Malta',
	'tirana': 'Europe/Tirane',
	'skopje': 'Europe/Skopje',
	'sarajevo': 'Europe/Sarajevo',
	'podgorica': 'Europe/Podgorica',
	'chisinau': 'Europe/Chisinau',
	'ljubljiana': 'Europe/Ljubljana',
	'pristina': 'Europe/Belgrade',
	'vaduz': 'Europe/Vaduz',
	'monaco': 'Europe/Monaco',
	'sanmarinicity': 'Europe/San_Marino',
	'vaticancity': 'Europe/Vatican',
	'andorralavella': 'Europe/Andorra',

	// Cities — Americas
	'newyork': 'America/New_York',
	'newyorkcity': 'America/New_York',
	'nyc': 'America/New_York',
	'boston': 'America/New_York',
	'washingtondc': 'America/New_York',
	'washington': 'America/New_York',
	'miami': 'America/New_York',
	'orlando': 'America/New_York',
	'atlanta': 'America/New_York',
	'philadelphia': 'America/New_York',
	'detroit': 'America/Detroit',
	'chicago': 'America/Chicago',
	'houston': 'America/Chicago',
	'dallas': 'America/Chicago',
	'sanantonio': 'America/Chicago',
	'austin': 'America/Chicago',
	'minneapolis': 'America/Chicago',
	'kansascity': 'America/Chicago',
	'nashville': 'America/Chicago',
	'milwaukee': 'America/Chicago',
	'stlouis': 'America/Chicago',
	'neworleans': 'America/Chicago',
	'denver': 'America/Denver',
	'phoenix': 'America/Phoenix',
	'saltlakecity': 'America/Denver',
	'albuquerque': 'America/Denver',
	'tucson': 'America/Phoenix',
	'losangeles': 'America/Los_Angeles',
	'la': 'America/Los_Angeles',
	'sanfrancisco': 'America/Los_Angeles',
	'sf': 'America/Los_Angeles',
	'seattle': 'America/Los_Angeles',
	'portland': 'America/Los_Angeles',
	'lasvegas': 'America/Los_Angeles',
	'sandiego': 'America/Los_Angeles',
	'sanjose': 'America/Los_Angeles',
	'sacramento': 'America/Los_Angeles',
	'anchorage': 'America/Anchorage',
	'honolulu': 'Pacific/Honolulu',
	'toronto': 'America/Toronto',
	'montreal': 'America/Toronto',
	'ottawa': 'America/Toronto',
	'vancouver': 'America/Vancouver',
	'calgary': 'America/Edmonton',
	'edmonton': 'America/Edmonton',
	'winnipeg': 'America/Winnipeg',
	'mexicocity': 'America/Mexico_City',
	'guadalajara': 'America/Mexico_City',
	'monterrey': 'America/Monterrey',
	'tijuana': 'America/Tijuana',
	'cancun': 'America/Cancun',
	'puebla': 'America/Mexico_City',
	'saopaulo': 'America/Sao_Paulo',
	'riodejaneiro': 'America/Sao_Paulo',
	'rio': 'America/Sao_Paulo',
	'brasilia': 'America/Sao_Paulo',
	'manaus': 'America/Manaus',
	'buenosaires': 'America/Argentina/Buenos_Aires',
	'bogota': 'America/Bogota',
	'medellin': 'America/Bogota',
	'cali': 'America/Bogota',
	'lima': 'America/Lima',
	'santiago': 'America/Santiago',
	'caracas': 'America/Caracas',
	'quito': 'America/Guayaquil',
	'guayaquil': 'America/Guayaquil',
	'lapaz': 'America/La_Paz',
	'sucre': 'America/La_Paz',
	'asuncion': 'America/Asuncion',
	'montevideo': 'America/Montevideo',
	'panamacity': 'America/Panama',
	'sanjosecostarica': 'America/Costa_Rica',
	'havana': 'America/Havana',
	'kingston': 'America/Jamaica',
	'portauprince': 'America/Port-au-Prince',
	'santodomingo': 'America/Santo_Domingo',
	'guatemalacity': 'America/Guatemala',
	'tegucigalpa': 'America/Tegucigalpa',
	'sansalvador': 'America/El_Salvador',
	'managua': 'America/Managua',
	'belizecity': 'America/Belize',
	'nassau': 'America/Nassau',
	'bridgetown': 'America/Barbados',
	'portofspain': 'America/Port_of_Spain',
	'sanjuan': 'America/Puerto_Rico',
	'georgetown': 'America/Guyana',
	'paramaribo': 'America/Paramaribo',

	// Cities — Oceania
	'sydney': 'Australia/Sydney',
	'melbourne': 'Australia/Melbourne',
	'brisbane': 'Australia/Brisbane',
	'perth': 'Australia/Perth',
	'adelaide': 'Australia/Adelaide',
	'darwin': 'Australia/Darwin',
	'canberra': 'Australia/Sydney',
	'goldcoast': 'Australia/Brisbane',
	'auckland': 'Pacific/Auckland',
	'wellington': 'Pacific/Auckland',
	'christchurch': 'Pacific/Auckland',
	'suva': 'Pacific/Fiji',
	'portmoresby': 'Pacific/Port_Moresby',
	'honiara': 'Pacific/Guadalcanal',
	'portville': 'Pacific/Efate',
	'apia': 'Pacific/Apia',
	'nukualofa': 'Pacific/Tongatapu',

	// Cities — Africa
	'johannesburg': 'Africa/Johannesburg',
	'capetown': 'Africa/Johannesburg',
	'durban': 'Africa/Johannesburg',
	'pretoria': 'Africa/Johannesburg',
	'lagos': 'Africa/Lagos',
	'abuja': 'Africa/Lagos',
	'kano': 'Africa/Lagos',
	'ibadan': 'Africa/Lagos',
	'nairobi': 'Africa/Nairobi',
	'mombasa': 'Africa/Nairobi',
	'cairo': 'Africa/Cairo',
	'alexandria': 'Africa/Cairo',
	'accra': 'Africa/Accra',
	'addisababa': 'Africa/Addis_Ababa',
	'daressalaam': 'Africa/Dar_es_Salaam',
	'dodoma': 'Africa/Dar_es_Salaam',
	'khartoum': 'Africa/Khartoum',
	'casablanca': 'Africa/Casablanca',
	'rabat': 'Africa/Casablanca',
	'tunis': 'Africa/Tunis',
	'algiers': 'Africa/Algiers',
	'oran': 'Africa/Algiers',
	'tripoli': 'Africa/Tripoli',
	'kampala': 'Africa/Kampala',
	'harare': 'Africa/Harare',
	'bulawayo': 'Africa/Harare',
	'lusaka': 'Africa/Lusaka',
	'maputo': 'Africa/Maputo',
	'dakar': 'Africa/Dakar',
	'kinshasa': 'Africa/Kinshasa',
	'lubumbashi': 'Africa/Lubumbashi',
	'luanda': 'Africa/Luanda',
	'antananarivo': 'Indian/Antananarivo',
	'kigali': 'Africa/Kigali',
	'douala': 'Africa/Douala',
	'yaounde': 'Africa/Douala',
	'abidjan': 'Africa/Abidjan',
	'bamako': 'Africa/Bamako',
	'ouagadougou': 'Africa/Ouagadougou',
	'conakry': 'Africa/Conakry',
	'mogadishu': 'Africa/Mogadishu',
	'windhoek': 'Africa/Windhoek',
	'gaborone': 'Africa/Gaborone',
	'portlouis': 'Indian/Mauritius',
	'niamey': 'Africa/Niamey',
	'ndjamena': 'Africa/Ndjamena',
	'bangui': 'Africa/Bangui',
	'libreville': 'Africa/Libreville',
	'brazzaville': 'Africa/Brazzaville',
	'malabo': 'Africa/Malabo',
	'bujumbura': 'Africa/Bujumbura',
	'portonovo': 'Africa/Porto-Novo',
	'lome': 'Africa/Lome',
	'freetown': 'Africa/Freetown',
	'monrovia': 'Africa/Monrovia',
	'bissau': 'Africa/Bissau',
	'banjul': 'Africa/Banjul',
	'nouakchott': 'Africa/Nouakchott',
	'blantyre': 'Africa/Blantyre',
	'lilongwe': 'Africa/Blantyre',
	'maseru': 'Africa/Maseru',
	'mbabane': 'Africa/Mbabane',
	'djibouti': 'Africa/Djibouti',
	'asmara': 'Africa/Asmara',
	'praia': 'Atlantic/Cape_Verde',
	'saotome': 'Africa/Sao_Tome',
	'moroni': 'Indian/Comoro',
	'victoria': 'Indian/Mahe',
};

// US timezone abbreviations
const ABBREV_TIMEZONES: Record<string, string> = {
	'est': 'America/New_York',
	'eastern': 'America/New_York',
	'cst': 'America/Chicago',
	'central': 'America/Chicago',
	'mst': 'America/Denver',
	'mountain': 'America/Denver',
	'pst': 'America/Los_Angeles',
	'pacific': 'America/Los_Angeles',
	'akst': 'America/Anchorage',
	'alaska': 'America/Anchorage',
	'hst': 'Pacific/Honolulu',
	'hawaii': 'Pacific/Honolulu',
	'gmt': 'Etc/GMT',
	'utc': 'Etc/UTC',
};

function resolveMultiAlias(key: string): [string, string][] | null {
	let entry = MULTI_TIMEZONE_COUNTRIES[key];
	// Follow string aliases (e.g. 'us' -> 'usa')
	if (typeof entry === 'string') entry = MULTI_TIMEZONE_COUNTRIES[entry];
	return Array.isArray(entry) ? entry : null;
}

function parseUTCOffset(input: string): number | null {
	let str = input.replace(/\+$/, '').trim();
	const sign = str.startsWith('-') ? -1 : 1;
	str = str.replace(/^[+-]/, '');

	let hours = 0;
	let minutes = 0;

	if (str.includes(':')) {
		const parts = str.split(':');
		hours = parseInt(parts[0], 10);
		minutes = parseInt(parts[1] || '0', 10);
	} else if (str.includes('.')) {
		const f = parseFloat(str);
		hours = Math.floor(f);
		minutes = Math.round((f - hours) * 60);
	} else if (str.length > 2) {
		hours = parseInt(str.slice(0, -2), 10);
		minutes = parseInt(str.slice(-2), 10);
	} else {
		hours = parseInt(str, 10);
		minutes = 0;
	}

	if (isNaN(hours) || isNaN(minutes)) return null;
	if (Math.abs(hours) > 14 || minutes >= 60) return null;

	return sign * (hours * 60 + minutes);
}

function formatForTimezone(date: Date, timezone: string): string {
	return date.toLocaleString('en-US', {
		timeZone: timezone,
		weekday: 'short',
		year: 'numeric',
		month: 'short',
		day: 'numeric',
		hour: '2-digit',
		minute: '2-digit',
		second: '2-digit',
		hour12: true,
		timeZoneName: 'short',
	});
}

function formatForOffset(date: Date, offsetMinutes: number): string {
	const sign = offsetMinutes >= 0 ? '+' : '-';
	const absMinutes = Math.abs(offsetMinutes);
	const h = Math.floor(absMinutes / 60);
	const m = absMinutes % 60;
	const label = m === 0 ? `UTC${sign}${h}` : `UTC${sign}${h}:${String(m).padStart(2, '0')}`;

	const utcMs = date.getTime() + date.getTimezoneOffset() * 60000;
	const shiftedDate = new Date(utcMs + offsetMinutes * 60000);

	const pad = (n: number) => String(n).padStart(2, '0');
	const days = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
	const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

	let hours = shiftedDate.getUTCHours();
	const ampm = hours >= 12 ? 'PM' : 'AM';
	hours = hours % 12 || 12;

	return (
		`${days[shiftedDate.getUTCDay()]}, ` +
		`${months[shiftedDate.getUTCMonth()]} ${shiftedDate.getUTCDate()}, ` +
		`${shiftedDate.getUTCFullYear()} ` +
		`${pad(hours)}:${pad(shiftedDate.getUTCMinutes())}:${pad(shiftedDate.getUTCSeconds())} ${ampm} ` +
		`(${label})`
	);
}

function toTitleCase(str: string): string {
	return str.replace(/\b\w/g, c => c.toUpperCase());
}

export const commands: Chat.ChatCommands = {
	time(target, room, user, connection, cmd, message) {
		if (!this.runBroadcast()) return;

		const query = target.trim();

		if (!query) {
			return this.sendReplyBox(`🕐 <b>Current UTC Time:</b> ${formatForOffset(new Date(), 0)}`);
		}

		const now = new Date();

		// UTC offset input: e.g. "5:30", "+5:30", "-8", "5:30+"
		if (/^[+-]?\d[\d:.]*\+?$/.test(query)) {
			const offsetMinutes = parseUTCOffset(query);
			if (offsetMinutes === null) {
				return this.errorReply(`Invalid UTC offset "${query}". Use formats like: 5:30, +5:30, -8, 5.5`);
			}
			const absMin = Math.abs(offsetMinutes);
			const sign = offsetMinutes >= 0 ? '+' : '-';
			const label = `UTC${sign}${Math.floor(absMin / 60)}${absMin % 60 ? ':' + String(absMin % 60).padStart(2, '0') : ''}`;
			return this.sendReplyBox(`<b>Current Time (${label}):</b> ${formatForOffset(now, offsetMinutes)}`);
		}

		const lookupKey = toID(query);

		// Multi-timezone country (e.g. usa, canada, australia)
		const multiZones = resolveMultiAlias(lookupKey);
		if (multiZones) {
			const rows = multiZones.map(([label, tz]) => {
				try {
					return `<tr><td><b>${label}</b></td><td>${formatForTimezone(now, tz)}</td></tr>`;
				} catch (e) {
					return '';
				}
			}).filter(Boolean).join('');
			return this.sendReplyBox(
				`<b>Current Times in ${toTitleCase(query)}:</b><br>` +
				`<table style="border-collapse:collapse;margin-top:4px">${rows}</table>`
			);
		}

		// Abbreviation / timezone shorthand (EST, PST, etc.)
		if (ABBREV_TIMEZONES[lookupKey]) {
			const tz = ABBREV_TIMEZONES[lookupKey];
			return this.sendReplyBox(`<b>Current Time (${query.toUpperCase()}):</b> ${formatForTimezone(now, tz)}`);
		}

		// Single-timezone country or city lookup
		if (SINGLE_TIMEZONES[lookupKey]) {
			const tz = SINGLE_TIMEZONES[lookupKey];
			try {
				return this.sendReplyBox(`<b>Current Time in ${toTitleCase(query)}:</b> ${formatForTimezone(now, tz)}`);
			} catch (e) {
				return this.errorReply(`Error formatting time for "${query}".`);
			}
		}

		if (query.includes('/')) {
			try {
				return this.sendReplyBox(`<b>Current Time (${query}):</b> ${formatForTimezone(now, query)}`);
			} catch (e) {
			}
		}

		this.errorReply(`Unknown location "${query}". Try a country (india, usa), city (mumbai, tokyo, new york), or UTC offset (5:30, -8).`);
	},
	
	timehelp: [
		`/time [location|offset] - Shows the current time for a country, city, or UTC offset.`,
		`Examples: /time india | /time usa | /time mumbai | /time tokyo | /time new york | /time 5:30 | /time -8`,
		`Multi-timezone countries (usa, canada, australia, russia, brazil) show all zones.`,
		`Broadcastable with !time.`,
	],
};
